### ISSUE TITLE
Firewall Policies are changed when new peer are added

### ISSUE THREAD

**Issue by samboman** [vchrizz/ER-wizard-WireGuard#9]
When I add a new peer, my firewall policies that uses the wg0-interface, are changed (removed).

Before I add new peer:
![image](https://user-images.githubusercontent.com/1038277/186096246-f2fb23e3-373f-4734-966c-b4f26b436224.png)

After peer are added:
![image](https://user-images.githubusercontent.com/1038277/186096315-2bb489be-6a19-4319-89ad-3a26220ceb75.png)

I manually have to assign interfaces to these rules after new peer are added.

**Comment by vchrizz** [comment]
I could not reproduce the issue, I do not use firewall on the edgerouter so I would need more input and/or help to reproduce the issue to possibly fix this.
The wizard itself does nothing with firewall rules or settings, so I doubt the wizard is the cause for anything related to the firewall.
Could you try to reproduce the issue on command line?
You can do `show configuration commands | grep wireguard` via ssh on the router to get the wireguard config commands.
If the issue also happens when you add peers on command line, I would post that issue to [WireGuard/wireguard-vyatta-ubnt](https://github.com/WireGuard/wireguard-vyatta-ubnt/issues).
Else feel free to reopen.
